---
- name: Deploy CI/CD and target app
  hosts: cicd
  become: yes
  roles:
    - common
    - nginx_target

- name: Deploy WAF
  hosts: waf
  become: yes
  roles:
    - common
    - waf
    - fluent-bit

- name: Deploy OpenSearch
  hosts: opensearch
  become: yes
  roles:
    - common
    - opensearch
